### ISSUE TITLE
Documentation for the same? 

### ISSUE THREAD

**Issue by ghost** [CodeWithSwastik/dcoder#5]
Is there a documentation link? Is there going to be documentation? 
Because in the README, there are quite a few functions listed. 

Would this have some documentation, for the arguments and classes, functions. Is the documentation being made? 
For me to download the module I would need to find some use for it, and without docs no module is good.

**Comment by CodeWithSwastik** [comment]
The functions listed in the README are all the functions that are in the module for now. The functions are very self explanatory too. The module won't need documentation till we add some more  features _which I am planning to add soon_

**Comment by ghost** [comment]
Pin this m8, many people care about docs in APIs

**Comment by CodeWithSwastik** [comment]
The docs have been made and can view them here: https://dcoder.readthedocs.io/en/latest/
